### ISSUE TITLE
rename app

### ISSUE THREAD

**Issue by zassmin** [WomenWhoCode/wwcode_api#4]
please rename to `wwcode_api`

**Comment by zassmin** [comment]
We want the rails app to be renamed, this is a suggestion on how to do so: http://stackoverflow.com/questions/20988813/how-to-rename-rails-4-app

**Comment by timchai** [comment]
Renamed app to wwcode_api

**Comment by zassmin** [comment]
@timchai thanks for your changes! Same here, a review process would be helpful. 

RE: https://github.com/WomenWhoCode/wwcode_api/commit/539b7b327b2df37a31bf320e4f894b119831b7b4

The gem doesn't need to be committed, it just needed to be used to run the changes. 

Also, there are more changes to be made, you'll notice other areas that need changing by running a search in the app with the previous app name `ww-code-api`.  

I encourage you to submit a pull request with the additional changes.

**Comment by timchai** [comment]
Created pull request.
