### ISSUE TITLE
Remove config/database.yml or set up ENV variables to use

### ISSUE THREAD

**Issue by littleforest** [WomenWhoCode/wwcode_api#42]
Is it possible to remove the `config/database.yml` file altogether (not sure where you are hosting), so we can make local changes to it without dirtying the file?  If the hosting service requires it, can we set up environment variables to be used for username/password instead of hard-coding on dev/test environments?

**Comment by zassmin** [comment]
@littleforest yes, you are right! We need to do something about this. The way we handle this in our website repo is by putting the `config/database.yml` in the gitignore and provide steps on how to set up the local pg db https://github.com/WomenWhoCode/website/wiki/Postgresql-Localhost-Setup.

We use heroku which doesn't rely on database.yml. If we removed the database.yml, how would the db work for local and testing envs?

**Comment by littleforest** [comment]
@zassmin, for Heroku I put `config/database.yml` in .gitignore and commit a `config/database.yml.example` file and put instructions in the README for users to copy it to `config/database.yml` and edit as needed.  Will that work for this project do you think?
