### ISSUE TITLE
add contributing documentation

### ISSUE THREAD

**Issue by zassmin** [WomenWhoCode/wwcode_api#7]
copy most of section contributing and developing a feature https://github.com/WomenWhoCode/WomenWhoCode#contributing-and-developing-a-feature

**Comment by timchai** [comment]
Added contributing documentation.

**Comment by zassmin** [comment]
@timchai I could have given more detail here. The point of this issue is to kick of the Pull Request review process that we will start doing for each commit and issue. 

https://github.com/WomenWhoCode/WomenWhoCode#contributing-and-developing-a-feature was not suppose to be copied verbatim, there is language there that is Android specific. This is the point of a review process, it allows for that level of feedback when something is missed or could be improved. 

I encourage you to submit a PR with your README change and follow the steps in https://github.com/WomenWhoCode/WomenWhoCode#contributing-and-developing-a-feature and edit the language for information that is applicable to this project.

**Comment by timchai** [comment]
Oops.  I did make some minor adjustments.

**Comment by zassmin** [comment]
@timchai where is the pull request?

**Comment by timchai** [comment]
Now I'm understanding what you were requesting.  Sorry about that.  I did the pull request for the rename.

**Comment by zassmin** [comment]
closed by various commits

**Comment by littleforest** [comment]
@zassmin I actually couldn't seem to push to this main branch, and had to create a fork instead.  I'm wondering if the instructions should be updated to reflect that if you are a non-admin user.

**Comment by zassmin** [comment]
@littleforest great point. I'll reopen.

**Comment by littleforest** [comment]
great, I'll try to update this weekend.
